/*
 * Copyright (C) 2020 Leonardo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package frames;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import sistemacaixamercado.Carrinho;
import sistemacaixamercado.Produto;

/**
 * Um Callback é utilizado para mandar dados da compra realizada para a janela que
 * criou o CompraFrame. O método `callback` é chamado assim que a janela de compra
 * é fechada.
 * @author Leonardo
 */
interface Callback {
    public void callback(Carrinho carrinho);
}

/**
 *
 * @author Leonardo
 */
public class CompraFrame extends javax.swing.JFrame {
    private ArrayList<Produto> produtos;
    private Carrinho carrinho;
    private Callback cb;
    
    /**
     * Creates new form CompraFrame
     */
    public CompraFrame(ArrayList<Produto> produtos, Callback cb) {
        this.produtos = produtos;
        this.carrinho = new Carrinho();
        carrinho.add(new Produto(1, 500, "Leite", "leite"), 2);
        this.cb = cb;
        initComponents();
        
        initItensList();
        
    }
    
    private void initItensList() {
        DefaultListModel model = new DefaultListModel();
        for (Object obj : carrinho.getItens()) {
            model.addElement(obj);
        }
        itensList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itensList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-shopping-32.png"))); // NOI18N
        jLabel1.setText("Nova Compra");

        itensList.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itensList.setCellRenderer(new ItemCarrinhoRenderer());
        jScrollPane1.setViewportView(itensList);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/market.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<sistemacaixamercado.ItemCarrinho> itensList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
